import type { PlanOption } from './api'
import type { CustomStep } from '../components/CustomSteps'

/**
 * Opens a print-ready itinerary in a new tab and triggers the print dialog —
 * the OS "Save as PDF" path works on every platform (iOS: share → print),
 * costs zero bundle bytes, and the document carries the full brand.
 */
export function exportPlanPdf(args: {
  option: PlanOption
  routeLabel: string
  arriveBy: string
  nights: number
  shareUrl: string | null
  planKey: string
}) {
  const { option, routeLabel, arriveBy, nights, shareUrl, planKey } = args

  let additions: CustomStep[] = []
  try {
    additions = JSON.parse(localStorage.getItem('mg-plan-notes:' + planKey) || '[]')
  } catch {
    /* additions are optional */
  }

  const esc = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

  const stepRows = option.steps
    .map(
      (s) => `
      <tr class="${s.kind === 'main' ? 'main' : ''}">
        <td class="time">${esc(s.time)}</td>
        <td>
          <div class="label">${esc(s.label)}</div>
          <div class="sub">${esc([s.location, s.detail].filter(Boolean).join(' · '))}</div>
        </td>
        <td class="cost">${s.cost ? esc(s.cost) : ''}</td>
      </tr>`
    )
    .join('')

  const additionRows = additions
    .map(
      (a) => `
      <tr>
        <td class="time">${esc(a.time || '—')}</td>
        <td><div class="label">${esc(a.label)}</div></td>
        <td></td>
      </tr>`
    )
    .join('')

  const costRows = option.costBreakdown
    .map((c) => `<tr><td>${esc(c.label)}</td><td class="cost">$${c.amount}</td></tr>`)
    .join('')

  const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>Meguaz — ${esc(routeLabel)}</title>
<style>
  @page { margin: 14mm; }
  * { margin: 0; box-sizing: border-box; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  body { font: 13px/1.5 'Figtree', system-ui, sans-serif; color: #201e1d; background: #fff; padding: 32px; max-width: 720px; margin: 0 auto; }
  .head { display: flex; align-items: center; gap: 14px; padding-bottom: 18px; border-bottom: 2px solid #c67139; }
  .head img { width: 56px; height: 56px; }
  .head h1 { font-size: 24px; font-weight: 800; letter-spacing: -0.01em; }
  .head .tag { font-size: 11px; letter-spacing: 0.18em; text-transform: uppercase; color: #82796a; margin-top: 2px; }
  .meta { display: flex; flex-wrap: wrap; gap: 20px; margin: 16px 0 22px; }
  .meta div { min-width: 110px; }
  .meta .k { font-size: 10px; letter-spacing: 0.1em; text-transform: uppercase; color: #82796a; }
  .meta .v { font-size: 15px; font-weight: 700; margin-top: 1px; }
  h2 { font-size: 14px; letter-spacing: 0.08em; text-transform: uppercase; color: #8c491a; margin: 22px 0 8px; }
  table { width: 100%; border-collapse: collapse; }
  td { padding: 8px 10px 8px 0; border-bottom: 1px solid #eee7db; vertical-align: top; }
  tr.main td { background: #fff2eb; border-bottom: 1px solid #ffc6a5; }
  tr.main .label { color: #8c491a; }
  .time { white-space: nowrap; font-weight: 700; width: 118px; color: #645c50; }
  .label { font-weight: 700; }
  .sub { color: #82796a; font-size: 11.5px; margin-top: 1px; }
  .cost { text-align: right; font-weight: 700; color: #8c491a; white-space: nowrap; width: 70px; }
  .total { display: flex; justify-content: space-between; align-items: baseline; margin-top: 10px; padding: 12px 14px; background: #f9f4ed; border-radius: 10px; }
  .total .amt { font-size: 22px; font-weight: 800; }
  .foot { margin-top: 26px; padding-top: 12px; border-top: 1px solid #eee7db; font-size: 11px; color: #82796a; }
  .foot a { color: #b2622d; word-break: break-all; }
</style>
</head>
<body>
  <div class="head">
    <img src="${window.location.origin}/android-chrome-192x192.png" alt="" />
    <div>
      <h1>${esc(routeLabel)}</h1>
      <div class="tag">Meguaz · Your journey, perfected</div>
    </div>
  </div>

  <div class="meta">
    <div><div class="k">Arrive by</div><div class="v">${esc(arriveBy)}</div></div>
    <div><div class="k">Trip length</div><div class="v">${nights} nights</div></div>
    <div><div class="k">Airline</div><div class="v">${esc(option.airline?.name ?? '—')}</div></div>
    <div><div class="k">Door to door</div><div class="v">${esc(option.doorToDoor)}</div></div>
    <div><div class="k">Leave home by</div><div class="v">${esc(option.leaveBy)}</div></div>
  </div>

  <h2>The plan, step by step</h2>
  <table>${stepRows}</table>

  ${additions.length > 0 ? `<h2>Your additions</h2><table>${additionRows}</table>` : ''}

  <h2>Costs</h2>
  <table>${costRows}</table>
  <div class="total"><span>Total trip cost</span><span class="amt">$${option.cost}</span></div>

  <div class="foot">
    ${shareUrl ? `Reopen or share this plan: <a href="${esc(shareUrl)}">${esc(shareUrl)}</a><br/>` : ''}
    Generated by Meguaz — real fares, door-to-gate plans, everything in one place.
  </div>
  <script>window.onload = function () { setTimeout(function () { window.print() }, 150) }</script>
</body>
</html>`

  const w = window.open('', '_blank')
  if (!w) return false
  w.document.write(html)
  w.document.close()
  return true
}
