// AUTO-GENERATED by the scenes worker — do not edit by hand.
// Three generated scenes per covered destination, served from public/media/scenes.

export const SCENE_CODES: string[] = ["ABJ", "ACC", "ADD", "AKL", "ALA", "ALG", "AMM", "AMS", "ANU", "ARN", "ASB", "ASM", "ASU", "ATH", "BAH", "BEG", "BEY", "BGF", "BGI", "BGW", "BJL", "BJM", "BKK", "BKO", "BOG", "BRU", "BTS", "BUD", "BWN", "BZE", "BZV", "CAI", "CCS", "CDG", "CGK", "CKY", "CMB", "CMN", "COO", "CPH", "DAC", "DAM", "DAR", "DEL", "DIL", "DLA", "DOH", "DOM", "DSS", "DUB", "DXB", "DYU", "EBB", "EZE", "FCO", "FIH", "FNA", "FNJ", "FRA", "FRU", "GBE", "GEO", "GND", "GRU", "GUA", "HAH", "HAN", "HAV", "HEL", "HIR", "HRE", "ICN", "IKA", "IST", "JFK", "JIB", "JNB", "JUB", "KBL", "KBP", "KEF", "KGL", "KHI", "KIN", "KIV", "KRT", "KTM", "KUL", "KWI", "LAD", "LBV", "LCA", "LFW", "LHR", "LIM", "LIS", "LJU", "LLW", "LOS", "LPB", "LUN", "LUX", "MAD", "MCT", "MEX", "MGA", "MGQ", "MJI", "MLA", "MLE", "MNL", "MPM", "MRU", "MSQ", "MSU", "MVD", "NAN", "NAS", "NBO", "NDJ", "NIM", "NKC", "NRT", "OSL", "OTP", "OUA", "OXB", "PAP", "PBH", "PBM", "PEK", "PNH", "POM", "POS", "PRG", "PRN", "PTY", "RAI", "RGN", "RIX", "ROB", "RUH", "SAH", "SAL", "SCL", "SDQ", "SEZ", "SHO", "SIN", "SJJ", "SJO", "SKB", "SKP", "SOF", "SSG", "SVD", "SVO", "SYD", "TAS", "TGD", "TGU", "TIA", "TLL", "TLV", "TMS", "TNR", "TPE", "TUN", "UBN", "UIO", "UVF", "VIE", "VNO", "VTE", "WAW", "WDH", "YYZ", "ZAG", "ZRH"]

const HAS = new Set(SCENE_CODES)

/** Scene image URLs for a destination code; empty when not generated. */
export function sceneUrls(code: string): string[] {
  if (!HAS.has(code)) return []
  return [1, 2, 3].map((n) => '/media/scenes/' + code + '-' + n + '.jpg')
}
